[package]
name = "better-peek"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "1.1.1"

[dev-dependencies]
hashers = { version = "1.0.1", default-features = false }
rand = "0.8.5"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
